### PR TITLE
LPS-86838 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @Camork   this needs more work to get this to work with maven.  Notice that the pom.xml is empty for the project-template-modules-ext.  So to get modules-ext support in maven, we are going to have to implement all of the logic that is in the gradle support but in maven.

**Comment by Camork** [comment]
Hey @gamerson , are you mean the work in maven plugin? it may take some time.

**Comment by gamerson** [comment]
Ok you can send this one back and we can move forward with gradle-only right now.

**Comment by Camork** [comment]
sent to [https://github.com/gamerson/liferay-portal/pull/242](https://github.com/gamerson/liferay-portal/pull/242)

**Pull request closed without merging**
